version: '3.7'
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    command: ['postgres', '-c', 'log_statement=all']
    environment:
      - POSTGRES_DB=tests
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    ports:
      - '5432:5432'

  postgres_isolated:
    image: postgres:10
    restart: unless-stopped
    environment:
      - POSTGRES_DB=tests
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    ports:
      - '5435:5432'
