[build]
  command = "cd ../../ && turbo run build --filter=app && cd apps/app"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[functions."send-notifications"]
schedule = "@hourly"

[functions."update-cache"]
schedule = "@daily"