name: 'Send alert notifications'
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  send_alert_notifications:
    name: 'Send alert notifications'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Request to server
        uses: simonboisset/action-cron-fetch@v2
        with:
          token: ${{secrets.CRON_SECRET}}
          key: 'x-cron-secret-key'
          url: https://pont-chaban-delmas.com/api/notification.sendNotifications
