name: 'Update api data'
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  update-api-data:
    name: Update api data
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Request to server
        uses: simonboisset/action-cron-fetch@v2
        with:
          token: ${{secrets.CRON_SECRET}}
          key: 'x-cron-secret-key'
          url: https://pont-chaban-delmas.com/api/alert.getApiData
